image:
  repository: rss3/notion-calendar

service:
  type: ClusterIP
  port: 3000

ingressRoute:
  enabled: true
  routes:
    - Host(`notion-calendar.nsl.xyz`)
  entrypoint:
    - web
    - websecure

envFrom:
  - secretRef:
      name: notion-calendar
