name: Build and Deploy
on:
  push:
    branches:
      - main
    tags:
      - v*
jobs:
  build:
    uses: NaturalSelectionLabs/Daedalus/.github/workflows/docker-tpl.yaml@main
    with:
      images: rss3/notion-calendar
      context: .
      dockerfile: ./Dockerfile
      platforms: linux/amd64
    secrets: inherit
  deploy-prod:
    uses: NaturalSelectionLabs/Daedalus/.github/workflows/deploy-tpl.yaml@main
    needs:
      - build
    with:
      images: rss3/notion-calendar
      tag: sha-${{ github.sha }}
      cluster: prod
      namespace: guardian
      chart: web-app
      releaseName: notion-calendar
      overrideFiles: |
        deploy/prod/values.yaml
    secrets: inherit
